version: "3.8"

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: liferay
    ports:
      - "3306:3306"
      - "33060:33060"
    volumes:
      - ./mnt/mysql/conf.d:/etc/mysql/conf.d
      - ./mnt/mysql/initdb.d:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql

  elasticsearch:
    image: elasticsearch:7.14.1
    environment:
      - discovery.type=single-node
      - cluster.name=LiferayElasticsearchCluster
      - xpack.security.enabled=false
      - network.bind_host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es-data:/usr/share/elasticsearch/data

  liferay:
    image: ibaiborodine/liferay-portal-ce:7.4.1-ga2-jdk8-buster
    depends_on:
      - mysql
      - elasticsearch
    environment:
      LIFERAY_RETRY_PERIOD_JDBC_PERIOD_ON_PERIOD_STARTUP_PERIOD_MAX_PERIOD_RETRIES: 10
      LIFERAY_JVM_OPTS: "-Xms2560m -Xmx4096m"
      LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_DRIVER_UPPERCASEC_LASS_UPPERCASEN_AME: "com.mysql.cj.jdbc.Driver"
      LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_PASSWORD: "password"
      LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_USERNAME: "root"
      LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_URL: "jdbc:mysql://mysql/liferay?characterEncoding=UTF-8&dontTrackOpenResources=true&holdResultsOpenOverStatementClose=true&useFastDateParsing=false&useUnicode=true&serverTimezone=GMT"
    ports:
      - "80:8080"
      - "11311:11311"
    volumes:
      - ./mnt/liferay/base:/etc/opt/liferay
      - lr-data:/opt/liferay/data/document_library
      - ./mnt/liferay/deploy:/opt/liferay/deploy

volumes:
  db-data:
  es-data:
  lr-data:
